
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:9000
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            
app:
  routes:
    landing:
      id-route: 1
      type-service: service
      exposure-route: /landing
      domain-route: https://landing-saveform.herokuapp.com
      path-route: /mkt/form
      port-route: 443
      headers-request:
        token: hello
      